name: Go API tests
run-name: ${{ github.actor }} is executing all Go tests!
on: [push]
jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.22.3'
      - name: Build
        run: |
          go build

